services:
  db-loader:
    build:
      context: ./db-loader
    image: db-loader:latest
    environment:
      DB_HOST: db
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db-data:/data
    secrets:
      - db_user
      - db_password
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: rankings
    volumes:
      - db-data:/data
      - ./data/initial/db:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 3  
      start_period: 10s
      timeout: 5s
  server:
    build:
      context: ./rankings
    image: server:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: rankings
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    depends_on:
      db-loader:
        condition: service_completed_successfully
  caddy:
    image: caddy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
volumes:
  db-data:
    name: db-data
    external: true
secrets:
  db_root_password:
    file: ./secret/db_root_password.txt
  db_user:
    file: ./secret/db_user.txt
  db_password:
    file: ./secret/db_password.txt