services:
  db-loader:
    build:
      context: ./db-loader
    image: db-loader:latest
    environment:
      DB_HOST: db
    volumes:
      - db-data:/data
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: negro1243.
    volumes:
      - db-data:/data
      - ./data/initial/rankings.sql:/docker-entrypoint-initdb.d/rankings.sql
    ports: 
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 3  
      start_period: 10s
      timeout: 5s
volumes:
  db-data:
    name: db-data
    external: true